### ISSUE TITLE
Active item

### ISSUE THREAD

**Issue by wizlif** [sebaferreras/Ionic3-MultiLevelSideMenu#1]
Is it possible to set a style for the currently active/selected page in the menu

**Comment by sebaferreras** [comment]
Sorry for such a late response @wizlif. Between today and tomorrow I'll update the demo to include how that can be done.

**Comment by sebaferreras** [comment]
@wizlif please get the latest version of the component (and also please read the readme.md file to see the overall changes). Now you can use the following settings to show the active page:

```
  // Settings for the SideMenuComponent
  public sideMenuSettings: SideMenuSettings = {
    // ...,
    showSelectedOption: true,
    selectedOptionClass: 'my-selected-option'
  };
```

And set the custom styling:

```
.my-selected-option {
    color: map-get($colors, primary);
    font-weight: 700;
}
```

And the result should be something like this:

![selectedoption](https://user-images.githubusercontent.com/17194770/29859255-7dcc2cd4-8d61-11e7-9375-5d26fe95a3cb.gif)

I'll close this issue, but feel free to re-open it if you need support. Thanks :)
