### ISSUE TITLE
it takes a long time to load the page

### ISSUE THREAD

**Issue by matiasAS** [sebaferreras/Ionic3-MultiLevelSideMenu#11]
Hi, I am using this menu with lazy loading of ionic 3, but the pages take me very long to open, any solution?

**Comment by sebaferreras** [comment]
I'm afraid that is not related to the component at all, but to Ionic itself. You can try by **preloading** the pages that take too long to load. You can find how to do that **[in IonicPage docs](https://ionicframework.com/docs/api/navigation/IonicPage/#priority)**.

I'll close this issue, but feel free to re-open it if you need any help with the side menu component :)

**Comment by matiasAS** [comment]
Hola Sebastián,
Lo que pasa es que si cargo todas las paginas en el app.module.ts, pierdo el lazy loading y no lo quiero perder

**Comment by sebaferreras** [comment]
No estoy muy seguro porque nunca lo probé, pero podrías probar de poner una prioridad `high` sólo en esas páginas, y poner prioridad `off` en todas las demás. Según la documentación:

>  If the priority is set to "off" the link will not be preloaded.

Eso debería permitirte prelodear sólo algunas páginas y dejar que las demás se carguen cuando se necesite.

**Comment by sebaferreras** [comment]
Primero en `app.module.ts`:

```
@NgModule({
  declarations: [
    MyApp
  ],
  imports: [
    BrowserModule,
    IonicModule.forRoot(MyApp, {
      preloadModules: true // <---------------- Activar esta configuración
    })
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    MyApp
  ]
})
export class AppModule { }
```

Y luego en cada página, si querés que se carguen de forma anticipada:

```
@IonicPage({ priority: 'high' })
@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage { ... } 
```

Y si querés que se carguen solo cuando se abren:

```
@IonicPage({ priority: 'off' })
@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage { ... } 
```

**Comment by matiasAS** [comment]
Pero hacer eso: " preloadModules: true /", es como perder el lazy loading o no?

**Comment by sebaferreras** [comment]
En teoría no, porque si a todas las páginas le asignas la prioridad en `off`, no se van a cargar. Es simplemente para poder cargar las que si quieras cargar (al asignar una prioridad de `high`).

**Comment by matiasAS** [comment]
Entonces, a todas las paginas que las tengo enlazadas en el sidemenu, le deberia agregar { priority: 'off' }, ademas de la otra linea
