### ISSUE TITLE
menu icon does not appear

### ISSUE THREAD

**Issue by ahmadlinus** [sebaferreras/Ionic3-MultiLevelSideMenu#12]
Hi, 
I wanted to use this, but when I added the stuff to my project, the menu toggle button would not be visible in page components. What do I need to make that happen? I already have a button in the toolbar with menuToggle. Please help me.

**Comment by sebaferreras** [comment]
Hi. I'm not sure if this is related to the component at all... Could you please check if you've added the `persistent="true"` attribute to the `ion-menu`, in the `app.component.html` file? It should look like this:

    <ion-menu persistent="true" [content]="content" ...> ... </ion-menu>

**Comment by sebaferreras** [comment]
I'll close this issue since it has been inactive for a long time. Feel free to re-open it if you need any help. Thanks :)
