### ISSUE TITLE
How we can do subMenu with submenu?

### ISSUE THREAD

**Issue by pranitaTp** [sebaferreras/Ionic3-MultiLevelSideMenu#15]
Home
Menu2
 ---submenu1
 ---submenu2
                  [---subsubmenu1]
Menu3

How can we do that?

**Comment by sebaferreras** [comment]
I'm afraid that just like you can see in the first lines of the README.md file,

> Ionic 2/3 demo of a two-level side menu. **The component currently supports only two levels of items. If more levels are needed, maybe using tabs layout for the other levels would be a better approach** 

that's not currently supported by this component. It may be added in the future but it's not the priority at the moment. Thanks :)
