### ISSUE TITLE
Don't collapse menu when selected sub item

### ISSUE THREAD

**Issue by tejas008** [sebaferreras/Ionic3-MultiLevelSideMenu#19]
I don't want to collapse my sub menu on select of sub menus. I am trying ti use this multilevel side menus on split pane .I want to show on my desktop.When i click on sub menu it should be open till we are on that page.

**Comment by sebaferreras** [comment]
Could you please take a look at this comment?: **https://github.com/sebaferreras/Ionic3-MultiLevelSideMenu/issues/31#issuecomment-380214310**

There you can find how to keep the side menu expanded after selecting options.
