### ISSUE TITLE
How can I set the menu heading color and font color?

### ISSUE THREAD

**Issue by peterennis** [sebaferreras/Ionic3-MultiLevelSideMenu#23]
I would like to be able to have a different color for the selected menu background.
Also a secondary color for the actual selected menu would be nice.
If it exists and is documented it must be in my blind spot :(

![capture222](https://user-images.githubusercontent.com/140737/33801835-a7df0a36-dd1c-11e7-94df-4bff327feb6f.png)

**Comment by sebaferreras** [comment]
Did you see the **[Theming section](https://github.com/sebaferreras/Ionic3-MultiLevelSideMenu#theming)**? You should be able to do that by using the CSS rules shown there.

**Comment by sebaferreras** [comment]
I'll close this issue since it is covered in the `Theming section` of the readme file. Feel free to re-open it if you need any help.

Thanks :)
