### ISSUE TITLE
SideMenu Direction

### ISSUE THREAD

**Issue by pratikgavas** [sebaferreras/Ionic3-MultiLevelSideMenu#25]
How to change the direction of a side menu?
Currently its left to right, but i want side menu from right to left.
Is there any option available for this?

**Comment by sebaferreras** [comment]
That could be done but it's not related to the component itself; you'd need to configure Ionic to add right-to-left support in the entire app (which would also make the side menu to work properly from right-to-left as well). 

I'll update the app to show how I did it in some apps I've been working on that use left-to-right and right-to-left modes.

**Comment by pratikgavas** [comment]
Thank you very much for this information and quick response. 👍

**Comment by pratikgavas** [comment]
Just we need to add side="right" attribute to <ion-menu>. :)

**Comment by sebaferreras** [comment]
Yes, that's right. And, just in case, you could also use the [css `direction` rule](https://developer.mozilla.org/en-US/docs/Web/CSS/direction) to set the direction of the items to be right-to-left or left-to-right as well :)
