### ISSUE TITLE
Menu not show on mobile

### ISSUE THREAD

**Issue by viniciosyals** [sebaferreras/Ionic3-MultiLevelSideMenu#26]
Whats is happening?
[Serve](https://i.imgur.com/wxxEHYh.png)
[Mobile](https://i.imgur.com/pMJbbwQ.png)

**Comment by sebaferreras** [comment]
Can't tell if I don't see the code. There's probably an error when/before the options are initialized.

Is there anything being shown in the console?

**Comment by viniciosyals** [comment]
@sebaferreras Nope, nothing in console. I followed exactly the steps that you did in README :/

I realized that some devices work and others dont. All devices is been updated, (The device that works is iOS)

**Comment by sebaferreras** [comment]
@viniciosyals could you please add the most relevant parts of the code?

**Comment by sebaferreras** [comment]
I'll close this issue; feel free to re-open it if you need any help. Thanks :)
