### ISSUE TITLE
Side Menu background image

### ISSUE THREAD

**Issue by Vickypr1902** [sebaferreras/Ionic3-MultiLevelSideMenu#30]
Unable to apply a background image in side menu..., and If I apply then it changes the background of the pages to which I navigate thru it..( I was using scroll-content to set an image on app.scss )   Any solution??

**Comment by Vickypr1902** [comment]
No issues, I figured it out. So closing this.

**Comment by sebaferreras** [comment]
Glad to hear that you solved the issue @Vickypr1902. The next update of the component will encapsulate the entire side menu (instead of the options only) and will make this and some other tasks much easier :)
