### ISSUE TITLE
Lazy loading??

### ISSUE THREAD

**Issue by daVinci13** [sebaferreras/Ionic3-MultiLevelSideMenu#34]
Converting it to lazy loading is a nightmare! I have been trying for (almost) a month now without any progress.... Any help is more than welcome.

**Comment by sebaferreras** [comment]
Sorry to hear that @daVinci13. I'll push a big update today/tomorrow; all the pages are lazy-loaded in that update.

**Comment by daVinci13** [comment]
@sebaferreras That would be fantastic!I'm working on a project based on this template and I had to add 35 new pages (on sub menu) which have huge impact on performance of the app.

**Comment by sebaferreras** [comment]
I've just pushed that update, I hope you can find there how to use lazy-loaded pages in the side menu. I'll be closing this issue but feel free to re-open it if you need any help. Thanks :)
