### ISSUE TITLE
npm WARN tsickle@0.24.1 requires a peer of typescript@2.4.2 but none is installed

### ISSUE THREAD

**Issue by peterennis** [sebaferreras/Ionic3-MultiLevelSideMenu#38]
I have an update running using Angular 6 here:
https://test.adaept.com/
with this repo:
https://github.com/peterennis/test-side-menu-content

However, I cannot seem to update your code as the tsickle WARN does
not allow TypeScript to be updated.

State of my fork is here: https://github.com/peterennis/Ionic3-MultiLevelSideMenu

tsickle relates to Closure, but I have no idea if you are using that or how.

Purpose
=====
Update prep for testing Ionic 4.

I removed ionic-native stuff as it will probably be using Capacitor.

Another repo will be needed for Ionic 4. Are you interested to
move forward on that?

I have some tests running:
https://aetabs.adaept.com
https://aeion4.adaept.com

This one:
https://aeicons.adaept.com/
Is using Ionic 3.9.2 with Angular 6

**Comment by sebaferreras** [comment]
> tsickle relates to Closure, but I have no idea if you are using that or how.

I'm not using it (at least not intentionally!).

> I removed ionic-native stuff as it will probably be using Capacitor.
> Another repo will be needed for Ionic 4. Are you interested to move forward on that?

Of course! But If it's ok for you @peterennis, let's wait for Ionic v4 to be released and then we update the component to that version. We can keep the Ionic 2/3+ version in a `ionic3` branch and update `master` to use Ionic 4/Capacitor

I'm closing this issue for now, we can then create a new issue as soon as Ionic 4 is released

**Comment by peterennis** [comment]
Ionic 4 is using Stencil components.
The next side menu, as a component, will have wider use potential in Vue, React etc.
