### ISSUE TITLE
 Add options dynamically

### ISSUE THREAD

**Issue by minchetas** [sebaferreras/Ionic3-MultiLevelSideMenu#39]
Hi. First of all thank you for this wonderful plugin and for sharing!!. 

I'm trying to create a menu from which I first know the main elements, but one of them is a submenu with elements that come from a web service ...

The fact is that once I have added the structure to the SideMenuOption, I can not find a way to modify or add more elements... even if I load some data in the option array after a timeout (as a test) these do not appear anymore!

The only way I have found is to retain the initialization of the application until the web service has answered, using the angular APP_INITIALIZER token, and then create the menu ... but that causes the screen to go blank for a while. :(

Is there a way to reset or reinitialize the menu once I have the necessary data?

TX.

**Comment by sebaferreras** [comment]
Hi @minchetas, thank you for your kind words and for using this plugin!

Could you please take a look at **[this comment](https://github.com/sebaferreras/Ionic3-MultiLevelSideMenu/issues/29#issuecomment-368403019)**? I think it's a pretty similar issue, but just in case:

> In order to improve the performance of the app, the side menu component uses OnPush as the change detection strategy.
> 
> The thing is that Angular does not recognize that the input has changed when you add/remove one item from that array. Instead, you'd need to change the entire array so Angular knows that this is a different array and the component should be updated.

So something like this should work:

```
// app.component.ts file
// I'm assuming "this.options" is the property bound to the html
// <side-menu-content [options]="options" ... ></side-menu-content>

// ...
const newOptions = methodThatUpdatesAllTheOptions();
this.options = [...newOptions]; // Replace the current options reference
// ...
```

**Comment by minchetas** [comment]
Thank you for your quick answer. I try and comment.

**Comment by sebaferreras** [comment]
I'm closing this issue since it's been more than 20 days since your last comment. Please feel free to re-open it if you need any help. Thanks for supporting this component :)
