### ISSUE TITLE
Side menu shrinks when sub option selected

### ISSUE THREAD

**Issue by peterennis** [sebaferreras/Ionic3-MultiLevelSideMenu#4]
It is better if the side menu sub options stay open when something is selected.
The current selected menu should be highlighted.
Sub Options should be indented.

**Comment by sebaferreras** [comment]
Hi @peterennis, thanks for your feedback. All your suggestions are actually great. I've updated the component a few minutes ago, so now you can use the `subOptionIndentation` setting to add some indentation to the sub items:

```
        // Settings for the SideMenuComponent
	public sideMenuSettings: SideMenuSettings = {
		accordionMode: true,
		showSelectedOption: true,
		selectedOptionClass: 'my-selected-option',
		subOptionIndentation: {
			md: '56px',
			ios: '64px',
			wp: '56px'
		}
	};
```
And the result will be something like this:

<img width="1280" alt="sidemenupadding" src="https://user-images.githubusercontent.com/17194770/30476147-63186146-9a09-11e7-8163-e31fd5eb16fe.png">

I've also improved the inner logic so if the currently selected option is a sub item, its parent will be shown expanded (only if the `showSelectedOption` setting was set to `true`):

![suboptionalwaysshown](https://user-images.githubusercontent.com/17194770/30476321-f779cdf2-9a09-11e7-8c8e-7c243e1f3e33.gif)

I'll close this issue, but please feel free to reopen it if you need any help. Thanks again for your feedback :)

**Comment by peterennis** [comment]
Great!
Looks good. I will let you know after I do some testing.
