### ISSUE TITLE
Back button on android to go home page

### ISSUE THREAD

**Issue by alegomez89** [sebaferreras/Ionic3-MultiLevelSideMenu#44]
Hi Seba, it's me again. I have a problem when I want to back to the home page pressing the back button of an a android phone, the problem occurs when I enter in a view and open a modal, then I close the modal but the back button do nothing, the idea when i press the is back button go to the home page, can you help me? Thanks for your time! 

Alejandro.

**Comment by sebaferreras** [comment]
Hi @alegomez89. I'm pretty sure that this is not related to the side menu, so I think it'd be better if you could write this question in StackOverflow (it'd be even better if you could create a [stackblitz demo](https://stackblitz.com/edit/ionic-emnxf7) with that issue so we can debug what's going on).
