### ISSUE TITLE
Property 'injector' does not exist on type 'typeof AppModule'.

### ISSUE THREAD

**Issue by meneva** [sebaferreras/Ionic3-MultiLevelSideMenu#45]
Hello,
I am trying to include your multilevelsideMenu into my ionic3 apps and it was running nicely. But all of a sudden it just showing me injector error "Property 'injector' does not exist on type 'typeof AppModule'." in custom-decorators/side-menu-display-text-conditions.decorator.ts file

**Comment by sebaferreras** [comment]
Hello @meneva. Could you please check if your `app.module.ts` file includes [these lines of code](https://github.com/sebaferreras/Ionic3-MultiLevelSideMenu/blob/master/src/app/app.module.ts#L28):

```
// ...
// ...
export class AppModule {
  // Make the injector to be available in the entire module
  // so we can use it in the custom decorator
  static injector: Injector;

  constructor(injector: Injector) {
    AppModule.injector = injector;
  }
}
```
