### ISSUE TITLE
Expand arrow does not show the select menu color

### ISSUE THREAD

**Issue by peterennis** [sebaferreras/Ionic3-MultiLevelSideMenu#5]
If I touch/click the expand menu I expect it to be blue.

![capture158](https://user-images.githubusercontent.com/140737/30466696-7a1e23b4-9994-11e7-9281-08642d705d9f.png)

**Comment by sebaferreras** [comment]
Hi, why would you expect that to be blue? Only the currently selected option will be assigned a given class that allows you to customize it (like changing the color).

Changing the color of any expanded option (if it's not the parent of the currently selected option) will be confusing in my opinion.

**Comment by peterennis** [comment]
Think of a tab menu. The one you click on gets the highlight color.
So in your example the blue menu should go black and the clicked/touched one
should become blue.
Then there is no confusion.
