### ISSUE TITLE
Hello, I want to ask how to fix the sidebar

### ISSUE THREAD

**Issue by zhanghui951684429** [sebaferreras/Ionic3-MultiLevelSideMenu#51]
Fix the side menu on the page only when the button is clicked. How can I do this?

**Comment by sebaferreras** [comment]
Hello! I don't quite understand your question. Could you please provide some more information/screenshots? Thanks :)

**Comment by sebaferreras** [comment]
Closing this issue because the question is not clear at all. Feel free to add a comment here or open a new one if you still need some help. Thanks.
