### ISSUE TITLE
Integrated the component but it does not show the page contents

### ISSUE THREAD

**Issue by peterennis** [sebaferreras/Ionic3-MultiLevelSideMenu#9]
How do I debug this? It opens the page but contents are not loaded.

![capture161](https://user-images.githubusercontent.com/140737/30574039-42ab0e4a-9cac-11e7-8e01-dcac78c2108b.png)
![capture162](https://user-images.githubusercontent.com/140737/30574044-484aed66-9cac-11e7-8d05-6cf6459ced56.png)

**Comment by sebaferreras** [comment]
I was not able to reproduce this issue. Could you please try to reproduce it using **[this Stackblitz project](https://stackblitz.com/edit/side-menu-sandbox)**?

**Comment by peterennis** [comment]
OK. It will take me a few days to get time.
FYI, my dev sandbox is where the component integration is being targeted.
The live page looks like this:

![capture1103](https://user-images.githubusercontent.com/140737/30941374-f106de26-a399-11e7-9527-b08b967065df.PNG)

**Comment by peterennis** [comment]
The sandbox does not work and the Ionic version is older than what I am using.
I will update to Ionic 3.7.0 and test again.

![capture183](https://user-images.githubusercontent.com/140737/30999164-450d5b32-a488-11e7-9091-806bbf6be727.png)

**Comment by sebaferreras** [comment]
Hmmm could you please try again? Becuase it's working on my end: 

<img width="1274" alt="stackblitz" src="https://user-images.githubusercontent.com/17194770/31008808-ac2a5cca-a505-11e7-9f25-885dfdc454cc.png">

And also please notice that the component was created using `ionic-angular 3.6.0`, not sure if it will work in `3.7.0` (until I test it and adapt it if needed).

**Comment by peterennisrda** [comment]
I have created an MVP and will commit  the test to GitHub.
Updated to 3.7.0 and the same problem exists.
I will let you know when it is available.

**Comment by peterennis** [comment]
Test repo here: https://github.com/peterennis/test-side-menu-content
Updated to Ionic 3.7.1
Error still exists.
If you are able to fix it I can turn the repo into a permanent testing sandbox.

**Comment by peterennis** [comment]
@sebaferreras, fixed in this commit: https://github.com/peterennis/test-side-menu-content/issues/2
It also works in my sandbox updated to Ionic 3.8.0
I am still a few commits behind and will continue testing with more menus.
